apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-sat-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: sat-app-pod1
  template:
    metadata:
      labels:
        app: sat-app-pod1
    spec:
      containers:
      - name: sat-app-container
        image: gcr.io/dps-parent-project/satdockerapp:v1.0.1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
