apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-sat-deployment
spec:
  selector:
    matchLabels:
      app: sat-app-pod1
  template:
    metadata:
      labels:
        app: sat-app-pod1
    spec:
      containers:
      - name: sat-app-container
        image: satapp:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
