apiVersion: apps/v1
kind: Deployment
metadata:
  name: satapp-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: satapp
  template:
    metadata:
      labels:
        app: satapp
    spec:
      containers:
      - name: satapp-container
        image: gcr.io/dps-parent-project/satapp:tagversion
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
