apiVersion: apps/v1
kind: Deployment
metadata:
  name: ed-app-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: ed-app
  template:
    metadata:
      labels:
        app: ed-app
    spec:
      containers:
      - name: ed-app-container
        image: gcr.io/dps-parent-project/ed-app:tagversion
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
